### ISSUE TITLE
MyCobot API is_moving() does'nt work

### ISSUE THREAD

**Issue by nisshan-x** [elephantrobotics/myCobotROS#5]
MyCobot API is_moving() does'nt work, when I call it in my ROS node. Then node dies.

```
Traceback (most recent call last):
  File "/home/nish/git/myCobotROS/scripts/pythonAPI/mycobot.py", line 226, in is_moving
    flag = int(data.hex(), 16)
AttributeError: 'str' object has no attribute 'hex'
```

**Comment by zlj-zz** [comment]
I've fixed this bug. You can pull the code again and view my commit information.

**Comment by nisshan-x** [comment]
That issue didn't happen with the latest commit in my environment. Thank you!
