### ISSUE TITLE
MyCobot.is_moving() always returns True

### ISSUE THREAD

**Issue by nisshan-x** [elephantrobotics/myCobotROS#6]
Procedure for reproducing: 
1. put MyCobot.is_moving() in control_slider.py
2. roslaunch myCobotROS control.launch 
3. rosrun myCobotROS control_slider.py

Return of MyCobot.is_moving() is always True, though myCobot stands still.

What is the difinition of moving in this API?

Thank you.

**Comment by nisshan-x** [comment]
In addition, I call MyCobot.stop(), but MyCobot.is_moving() always returns True.

Take a look, please.

**Comment by zlj-zz** [comment]
Don't worry, I'll fix it. I'll get back to you when I solve it.But it will take a while.

**Comment by zlj-zz** [comment]
When the problem was solved, you can find it in API change log. So I will close the issue
